# app 的唯一 id,上架到商店需要保证不要冲突,尽量使用开发者自己的域名作为后缀.
package: cloud.lazycat.app.liu.neko
# app 的版本
version: 3.0.0

name: Neko
keyword: neko
description: Neko 自托管虚拟浏览器

# 软件名称,会显示在启动器之类的地方
locales:
  zh:
    name: Neko 浏览器
    description: |
      ## Neko - 自托管虚拟浏览器

      **官方网站:** https://github.com/m1k1o/neko

      **仓库地址:** https://github.com/lazycatapps/neko.git

      Neko 是一个自托管的虚拟浏览器,运行在 Docker 容器中。它允许多用户通过 WebRTC 协议共享浏览器会话。

      本应用提供了完整的 Firefox 浏览器环境,支持远程访问和多用户协作。

      ## 主要功能

      - 🌐 完整的 Firefox 浏览器环境
      - 👥 支持多用户协作
      - 🎮 实时音视频传输
      - 🔒 安全的远程访问

      ## 使用方法

      ### 登录信息

      登录时可以使用**任意用户名**,通过输入的**密码**来确定你的角色权限:

      - **普通用户密码**: `neko` - 输入此密码将以普通用户身份登录
      - **管理员密码**: `admin` - 输入此密码将以管理员身份登录

      **⚠️ 安全提示**: 为了安全,强烈建议在首次使用后立即修改默认密码!

      ### 修改密码

      如需修改默认密码,请在应用配置中设置以下环境变量:

      - `NEKO_MEMBER_MULTIUSER_USER_PASSWORD` - 设置用户密码
      - `NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD` - 设置管理员密码

      ### WebRTC 配置

      应用会自动检测并配置懒猫微服虚拟公网地址 (fc03 开头的 IPv6)。

      如果自动检测失败,请手动获取懒猫盒子的 IPv6 地址并设置环境变量:

      - `NEKO_WEBRTC_NAT1TO1` - 手动指定懒猫盒子的 IPv6 地址

      例如: `NEKO_WEBRTC_NAT1TO1=fc03:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx`

  en:
    name: Neko Browser
    description: |
      ## Neko - Self-hosted Virtual Browser

      **Official Website:** https://github.com/m1k1o/neko

      **Repository:** https://github.com/lazycatapps/neko.git

      Neko is a self-hosted virtual browser that runs in Docker. It allows multiple users to share a browser session via WebRTC.

      This application provides a complete Firefox browser environment with remote access and multi-user collaboration support.

      ## Main Features

      - 🌐 Complete Firefox browser environment
      - 👥 Multi-user collaboration support
      - 🎮 Real-time audio and video streaming
      - 🔒 Secure remote access

      ## Usage Instructions

      ### Login Credentials

      You can use **any username** when logging in. Your role is determined by the **password** you enter:

      - **Regular user password**: `neko` - Enter this password to login as a regular user
      - **Admin password**: `admin` - Enter this password to login as an administrator

      **⚠️ Security Notice**: For security reasons, it is strongly recommended to change the default passwords after first use!

      ### Changing Passwords

      To change the default passwords, set the following environment variables in the application configuration:

      - `NEKO_MEMBER_MULTIUSER_USER_PASSWORD` - Set user password
      - `NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD` - Set admin password

      ### WebRTC Configuration

      The application will automatically detect and configure the Lazycat virtual public network address (IPv6 starting with fc03).

      If automatic detection fails, manually obtain your Lazycat box's IPv6 address and set the environment variable:

      - `NEKO_WEBRTC_NAT1TO1` - Manually specify your Lazycat box's IPv6 address

      Example: `NEKO_WEBRTC_NAT1TO1=fc03:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx`

# 软件本身的 license
license: https://choosealicense.com/licenses/apache-2.0/

# 软件的主页,会在商店等地方体现
homepage: https://github.com/m1k1o/neko

# lpk 的作者,会在商店等地方体现
author: liu

# application 作为一个特殊的 container 运行,对应的 service 名称为固定的`app`, 其他 service 可以通过此名称与 app 进行通讯
application:
  #是否存在后台任务, 若存在则系统不会对此 app 进行主动休眠等操作
  background_task: true

  # 期望的 app 域名,如果系统中已经有对应域名则会提示用户选择其他域名。 最终 app 分配到的域名以/lzcapp/run/app.subdomain 为准
  subdomain: neko

  routes:
    - /=http://host.lzcapp:59904

  # 无需登录即可访问的路径，该应用本身具有登录功能，无需系统二次登录。
  public_path:
    - /

  depends_on:
    - neko

  ingress:
    - protocol: tcp
      service: neko
      description: WebRTC TCP 端口范围
      publish_port: "52000-52100"
    - protocol: udp
      service: neko
      description: WebRTC UDP 端口范围
      publish_port: "52000-52100"

  # 是否启用多实例
  multi_instance: false

services:
  neko:
    image: registry.lazycat.cloud/liu/m1k1o/neko/firefox:f94bb56b03c7119b
    network_mode: host
    environment:
      - NEKO_DESKTOP_SCREEN=1920x1080@30
      - NEKO_MEMBER_MULTIUSER_USER_PASSWORD=neko
      - NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD=admin
      - NEKO_WEBRTC_EPR=52000-52100
      - NEKO_WEBRTC_UDPMUX=52000
      - NEKO_WEBRTC_TCPMUX=52000
      - NEKO_WEBRTC_ICELITE=1
      - NEKO_SERVER_BIND=host.lzcapp:59904
      # WebRTC NAT1TO1 地址将在 setup_script 中自动配置
    health_check:
      test:
        - CMD-SHELL
        # Neko 不支持 HEAD 请求(--spider)，使用 GET 请求但丢弃输出
        # 使用 timeout 强制 3 秒后终止，退出码 0(成功) 或 124(超时) 都视为健康
        - 'timeout 3 wget -q -O /dev/null http://host.lzcapp:59904 2>&1; ret=$$?; [ $$ret -eq 0 ] || [ $$ret -eq 124 ]'
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 10
    setup_script: |
      #!/bin/sh
      # 自动检测并配置 WebRTC NAT1TO1 地址
      # 使用 host 网络模式,可以直接读取宿主机的网络接口

      # 检查用户是否手动指定了地址
      if [ -n "$NEKO_WEBRTC_NAT1TO1" ]; then
        echo "======================================"
        echo "使用用户指定的 NAT1TO1 地址: $NEKO_WEBRTC_NAT1TO1"
        echo "======================================"
        export NEKO_WEBRTC_NAT1TO1
        return 0
      fi

      PUBLIC_IP=""
      echo "正在自动检测懒猫微服虚拟公网地址..."

      # 方案1: 从 /proc/net/if_inet6 读取 fc03 地址 (host 网络模式下可直接访问)
      if [ -f /proc/net/if_inet6 ]; then
        echo "[调试] 查找 fc03 地址 (子网掩码 /40 或 /28)..."
        cat /proc/net/if_inet6 | grep fc03

        # 提取 fc03 地址并转换格式
        # 格式: fc031136382e6b3f8e194ed77aca0000 04 28 00 80  heiyu-0
        # 转换为: fc03:1136:382e:6b3f:8e19:4ed7:7aca:0
        RAW_ADDR=$(cat /proc/net/if_inet6 2>/dev/null | grep fc03 | grep -E ' (28|40) ' | head -1 | awk '{print $1}')
        # 先转换格式,再简化前导零
        LAZYCAT_IP=$(echo "$RAW_ADDR" | \
          sed 's/\([0-9a-f]\{4\}\)/\1:/g' | \
          sed 's/:$//' | \
          sed 's/:0000/:0/g; s/:000\([0-9a-f]\)/:\1/g; s/:00\([0-9a-f]\)/:\1/g; s/:0\([0-9a-f][0-9a-f]\)/:\1/g')
        echo "[调试] 提取到的 fc03 地址: $LAZYCAT_IP"

        if [ -n "$LAZYCAT_IP" ]; then
          PUBLIC_IP="$LAZYCAT_IP"
          echo "✓ 成功检测到懒猫虚拟公网地址: $PUBLIC_IP"
        fi
      fi

      # 方案2: 如果没有 fc03,尝试获取真实公网 IPv6
      if [ -z "$PUBLIC_IP" ]; then
        echo "未检测到 fc03 地址,尝试获取真实公网 IPv6..."
        IPV6=$(wget -qO- -T 5 https://api64.ipify.org 2>/dev/null || curl -s -6 --max-time 5 https://api64.ipify.org 2>/dev/null || true)
        if [ -n "$IPV6" ] && echo "$IPV6" | grep -q ':'; then
          PUBLIC_IP="$IPV6"
          echo "✓ 检测到公网 IPv6 地址: $PUBLIC_IP"
        fi
      fi

      # 方案3: 获取 IPv4 地址
      if [ -z "$PUBLIC_IP" ]; then
        echo "未检测到 IPv6,尝试获取 IPv4 地址..."
        IPV4=$(wget -qO- -T 5 https://api.ipify.org 2>/dev/null || curl -s -4 --max-time 5 https://api.ipify.org 2>/dev/null || true)
        if [ -n "$IPV4" ]; then
          PUBLIC_IP="$IPV4"
          echo "✓ 检测到公网 IPv4 地址: $PUBLIC_IP"
        fi
      fi

      # 方案4: 最后回退方案
      if [ -z "$PUBLIC_IP" ]; then
        PUBLIC_IP=$(hostname -i | awk '{print $1}')
        echo "⚠ 警告: 无法获取公网 IP,使用主机 IP: $PUBLIC_IP"
        echo "⚠ WebRTC 可能无法正常工作"
      fi

      # 设置环境变量
      export NEKO_WEBRTC_NAT1TO1="$PUBLIC_IP"
      echo "======================================"
      echo "WebRTC NAT1TO1 已配置为: $NEKO_WEBRTC_NAT1TO1"
      echo "===================================="
